/* eslint-disable camelcase */
export const trailEndpoints = {
  login: '/user/login',
  socialLogin: '/user/nearLogin',
  signup: '/user/register',
  getAllTrails: '/userTourDataDetail/readTrailit_trails_data_tour',
  deleteTrailData: '/userTourDataDetail/deleteTrailit_trail_data_tour',
  getSingleTrailDataTrailId: '/userTourDataDetail/readTrailit_trails_data_tour',
  updateFollowTrail: '/userTourFollow/followUnfollowSingleTrail',
  getAllLikes: '/getLikes',
  createLikes: '/postLike',
  getAllComments: '/getAllCommentes',
  createComment: '/createComment',
  trailsList: '/userTourDataDetail/getTrailList',
  trailsListPublic: '/userTourDataDetail/getPublicTrailList',
  allPublicTrails: '/trailitUser/getAllCategory',
  checkCategoriesExist: '/trailitUser/checkCategoriesExists',
  addUpdateUserCategories: '/trailitUser/addUpdateUserCategories',
  tourDetails: '/userTourDataDetail/getTrailDataTourByTrailID',
  tourDetailsPublic: '/userTourDataDetail/getLimitedStepsData',
  addDeleteUserCategories: '/trailitUser/addDeleteUserCategories',
  updateFollowUser: '/userTourFollow/followUnfollowUser',
  getFollowUser: '/userTourFollow/getFollowEachUser',
  searchBy: '/userTourDataDetail/search',
  authorDetails: '/profileData/getProfileData',
  updateProfileData: '/profileData/addUpdateProfileData',
  getPaymentDetails: '/paymentData/getPaymentDetails',
  getCardDetails: '/paymentData/getCardDetails',
  addEditCardDetails: '/paymentData/addCardDetails',
  removeCardDetails: '/paymentData/removeCardDetails',
  profileImage: '/user/uploadUserProfilePic',
  uploadMedia: '/userTourDataDetail/uploadTrail_file_media',
  addUpdatePaymentDetails: '/paymentData/addUpdatePaymentDetails',
  followListEachUser: '/userTourFollow/getFollowListForEachUser',
  getAllNotification: '/trailItNotification/getAllNotifications',
  updateNotification: '/trailItNotification/updateNotificationFlag',
  clearNotifications: '/trailItNotification/clearNotifications',
  updateTrailTour: '/trailitUser/updateTrail_trail_user_tour',
  deleteSingleTrail: '/trailitUser/deleteSingleTrail',
  addEditTrailIntro: '/userTourDataDetail/addEditTrailIntro',
  nearDetails: '/user/getNearPublicKey',
  resendVerificationEmail: '/email/sendVerificationEmail',
  sendForgotPasswordMail: '/email/sendForgotPasswordEmail',
  resetPassword: '/user/resetPassword',
  verifyForgotPassword: '/email/verifyForgotPasswordEmail',
  logoutFromApp: '/user/logout',
  followListEachTrail: '/userTourFollow/getFollowListForEachTrail',
}

export const url = process.env.REACT_APP_URL
export const platformUrl = process.env.REACT_APP_PLATFORM_URL
export const SOCKET = process.env.REACT_APP_SOCKET
